# Generated by Django 5.2.8 on 2025-11-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_skill_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='required_skills',
            field=models.ManyToManyField(related_name='jobs', to='api.skill'),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='api.skill'),
        ),
    ]
