# Generated by Django 5.2.8 on 2026-01-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_profile_education_profile_experience_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_active',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
    ]
