# Generated by Django 5.2.8 on 2026-04-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_job_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='salary_range',
            field=models.CharField(default='Not specified', max_length=100),
        ),
    ]
