# Generated by Django 5.2.8 on 2026-04-05 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_category_job_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
